# Lab Week 10


### Part 1: Numpy

Just a few quick numpy questions

In [1]:
import numpy as np

In [2]:
#Create a 3x3 array of random number from 1-10
rand3x3 = np.random.randint(1,10,size=(3,3)) 
print(rand3x3)

[[5 4 5]
 [7 4 4]
 [4 6 6]]


In [3]:
#Give me just the 'corners' of this array 
#(hint: its every other row and every other column)
print(rand3x3[::2,::2])

[[5 5]
 [4 6]]


In [4]:
#Give me every multiple of 5, up to 100
range5 = np.arange(0,101,5)
print(range5)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


### Part 2: Beautiful Soup

Using HouseSoup (from the class notes), print out ever house member's name, political party, and state abbreviation. 

For instance, Boulder's congressman should look like: Joe Neguse (D-CO)

In [5]:
import requests
from bs4 import BeautifulSoup
houseXML = requests.get("http://clerk.house.gov/xml/lists/MemberData.xml").text
houseSoup = BeautifulSoup(houseXML,"lxml")

Some useful tags: 

official-name

state (you will have to get the postal-code from within this tag...)

party

In [6]:
#how do we iterate through all members?
for member in houseSoup.members.contents:
    
    #how do we get a member's name?
    name = member.find("official-name").text
    
    #how do we get a member's party?
    party=member.find("party").text
    
    #how do we get a member's state abbreviation?
    abbr = member.find("state")['postal-code']
    
    #make sure to only print filled seats!
    if(name):
        
        #how do we format and print that info?
        print('%s (%s-%s)' %(name,party,abbr))

Don Young (R-AK)
Bradley Byrne (R-AL)
Martha Roby (R-AL)
Mike Rogers (R-AL)
Robert B. Aderholt (R-AL)
Mo Brooks (R-AL)
Gary J. Palmer (R-AL)
Terri A. Sewell (D-AL)
Eric A. "Rick" Crawford (R-AR)
J. French Hill (R-AR)
Steve Womack (R-AR)
Bruce Westerman (R-AR)
Aumua Amata Coleman Radewagen (R-AS)
Tom O'Halleran (D-AZ)
Ann Kirkpatrick (D-AZ)
Raúl M. Grijalva (D-AZ)
Paul A. Gosar (R-AZ)
Andy Biggs (R-AZ)
David Schweikert (R-AZ)
Ruben Gallego (D-AZ)
Debbie Lesko (R-AZ)
Greg Stanton (D-AZ)
Doug LaMalfa (R-CA)
Jared Huffman (D-CA)
John Garamendi (D-CA)
Tom McClintock (R-CA)
Mike Thompson (D-CA)
Doris O. Matsui (D-CA)
Ami Bera (D-CA)
Paul Cook (R-CA)
Jerry McNerney (D-CA)
Josh Harder (D-CA)
Mark DeSaulnier (D-CA)
Nancy Pelosi (D-CA)
Barbara Lee (D-CA)
Jackie Speier (D-CA)
Eric Swalwell (D-CA)
Jim Costa (D-CA)
Ro Khanna (D-CA)
Anna G. Eshoo (D-CA)
Zoe Lofgren (D-CA)
Jimmy Panetta (D-CA)
TJ Cox (D-CA)
Devin Nunes (R-CA)
Kevin McCarthy (R-CA)
Salud O. Carbajal (D-CA)
Mike Garcia (R-CA)
Julia Br