### 1. Rapidfire Numpy

In [1]:
import numpy as np

In [7]:
#How can I get this array using numpy?
numpyArray= np.arange(0,100)
print(numpyArray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [9]:
#How can I get this array using numpy?
numpyArray =np.arange(0,300,3)
print(numpyArray)

[  0   3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48  51
  54  57  60  63  66  69  72  75  78  81  84  87  90  93  96  99 102 105
 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159
 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213
 216 219 222 225 228 231 234 237 240 243 246 249 252 255 258 261 264 267
 270 273 276 279 282 285 288 291 294 297]


In [11]:
#How can I get the previous array as a list?
list1 = list(numpyArray)
print(list1)

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99, 102, 105, 108, 111, 114, 117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150, 153, 156, 159, 162, 165, 168, 171, 174, 177, 180, 183, 186, 189, 192, 195, 198, 201, 204, 207, 210, 213, 216, 219, 222, 225, 228, 231, 234, 237, 240, 243, 246, 249, 252, 255, 258, 261, 264, 267, 270, 273, 276, 279, 282, 285, 288, 291, 294, 297]


In [24]:
#How can I make this 2D array?
numpyArray= np.arange(0,100).reshape(10,10)
numpyArray
newArray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(newArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
#How can we print just the 3rd column of the previous array?
print(newArray[0:,2])

[3 6 9]


In [27]:
#How can we print just the 2nd row of the previous array?
print(newArray[1,])

[4 5 6]


In [32]:
#how can we print every other row and every other column of the previous array?
print(newArray[::2,::2])

[[1 3]
 [7 9]]


In [28]:
#what are the dimensions of this array?
print(newArray.shape)

(3, 3)


### 2. Trickier Numpy

In [33]:
aBig2DArr = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14], [15,16,17,18,19],[20,21,22,23,24]])
print(aBig2DArr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [37]:
#how do we print out specific pieces of this array?
print(aBig2DArr[1:4,2:4]) # we can do slices of  columns and rows like that 

[[ 7  8]
 [12 13]
 [17 18]]


In [39]:
#create an array of 15 randomly selected numbers between 7 and 91
randomArray = np.random.randint(7,91,size=15)


In [43]:
#create an array of 15 perfectly spaced ascending numbers between 7 and 91


[ 7.          9.15384615 11.30769231 13.46153846 15.61538462 17.76923077
 19.92307692 22.07692308 24.23076923 26.38461538 28.53846154 30.69230769
 32.84615385 35.         37.15384615 39.30769231 41.46153846 43.61538462
 45.76923077 47.92307692 50.07692308 52.23076923 54.38461538 56.53846154
 58.69230769 60.84615385 63.         65.15384615 67.30769231 69.46153846
 71.61538462 73.76923077 75.92307692 78.07692308 80.23076923 82.38461538
 84.53846154 86.69230769 88.84615385 91.        ]


In [57]:
#generate a 2D array of randomly selected numbers between 7 and 91
#with 10 columns and 8 rows


[[17  9 50 87 25 10 27 23 35 23]
 [70 30 31 84 29 81 25 25 57 22]
 [14 71 16 46  7 66 35 42 83 61]
 [88 54 41 53  8 22 81 38 89 15]
 [10 36 40 32 58 87 75 25 18 71]
 [62 88 58 61 41 50 90 71 19 81]
 [36  9 90 43  8 70  8 54 71 50]
 [82 86 34 68 27 77 68 49 75 22]]


In [61]:
#using the previous array, create a new array that only includes:
#the numbers that are divisible by 2 and 16


[16 32]
