

## Problem 1  
Write a function that takes two lists as parameters. Your function should check if an element is in both lists.  After checking all elements, your function should print the following:  
  
These items are in both lists: (elements that are in both lists)  
These items are not in both lists: (elements that are not in both lists)  

For example, given  
  
listOne = ["a", "b", "c", "d"]  
and 
listTwo = ["c", "d", "e", "f"]  
  
your function would print  
  
These items are in both lists: c d  
These items are not in both lists: a b e f  

use the following function header:

def checkItemsInList(listOne, listTwo):

In [66]:
##1 
#your answer here
listOne = ["a", "b", "c", "d"]
listTwo = ["c", "d", "e", "f"]


def checkItemsInList(listOne, listTwo):
    inBoth = [] #create two empty lists to store words, one for words that are in both lists, one for words that are in only one
    inOne = []
    for item in listOne: #look at each item in listone
        if item in listTwo: # if item in list 2 
            inBoth.append(item)  # append inboth
        elif item not in listTwo:
            inOne.append(item) # else append inOne
    for item in listTwo: # if item in list 2 
        if item not in listOne: #and not in list 1 
            inOne.append(item)  #append inOne
    
    print("These items are in both lists: "+" ".join(inBoth))
    print("These items are in one list: "+ " ".join(inOne))

#Test Case 
listOne = ["a", "z", "x", "g","b","d"]
listTwo = ["c", "d", "e", "f","d","g","l"]
checkItemsInList(listOne,listTwo)

These items are in both lists: g d
These items are in one list: a z x b c e f l


## Problem 2

Let's use numpy with a Sudoku board. [Sudoku](https://en.wikipedia.org/wiki/Sudoku) is a puzzle game where a 9x9 board is completed if each row, column, and 3x3 tile has the values 1-9. The game starts with most of the values absent and the player fills out the grid through a process of elimination.

This is a "solved_board" as a test case:  

![Solved sudoku](http://i.imgur.com/etZoZkw.png)

In [67]:
import numpy as np
# let's keep it simple and make it a 9x9 array
solvedBoard = np.array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
                        [6, 7, 2, 1, 9, 5, 3, 4, 8],
                        [1, 9, 8, 3, 4, 2, 5, 6, 7],
                        [8, 5, 9, 7, 6, 1, 4, 2, 3],
                        [4, 2, 6, 8, 5, 3, 7, 9, 1],
                        [7, 1, 3, 9, 2, 4, 8, 5, 6],
                        [9, 6, 1, 5, 3, 7, 2, 8, 4],
                        [2, 8, 7, 4, 1, 9, 6, 3, 5],
                        [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [68]:
print(solvedBoard)

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


In [69]:
# Using numpy's accessing syntax, get the center item (single number) from the board
print(solvedBoard[4,4])

# now get the corners
# top-left
print(solvedBoard[0,0])
# top-right
print(solvedBoard[0,8])
# bottom-left
print(solvedBoard[8,0])
# bottom-right
print(solvedBoard[8,8])

5
5
2
3
9


In [70]:
# print the center 3x3 tile of the solved array
print(solvedBoard[3:6,3:6])   #using slices in numpy syntax 

[[7 6 1]
 [8 5 3]
 [9 2 4]]


In [71]:
# create a new array from every other row and every third column of the solved board

#same idea where we specify step sizes within a slice. (after two colons)
newArray = np.array(solvedBoard[::2,::3])
newArray

array([[5, 6, 9],
       [1, 3, 5],
       [4, 8, 7],
       [9, 5, 2],
       [3, 2, 1]])

In [43]:
# create a new array from the third through ninth columns and the first through
# fourth rows of the solved board

#using slice syntax again, we use 0 and 2 instead of 1 and 3 because of 0 indexes. 
newArray = np.array(solvedBoard[0:4:1,2:9:1])
newArray

array([[4, 6, 7, 8, 9, 1, 2],
       [2, 1, 9, 5, 3, 4, 8],
       [8, 3, 4, 2, 5, 6, 7],
       [9, 7, 6, 1, 4, 2, 3]])

In [73]:
# using loops, print out each 3x3 square of the solved board, moving from left to right.
# the 3x3 squares should be printed out as separate arrays. the less code you use for this
# problem, the more points you'll get.


#print all 9 squares of the board from left to right, bottom to top:

# We can print each square by looking at the values within each slice. 
# Minimum Slice value = 0,3,6,
# Maximum slice value = 3,6,9 OR min slice value + 3
# We want to look at the row first, so we get the minimimum row number in the slice. 
# We then get the minumum column number in the current slice.
# In the print statement, we take the minumum value for each slice as the start of the slice, and then that value+3 as the end of the slice 


for rownum in range(0,9,3):  #get minimum row slice values, 0, then 3, then 6
    for column in range(0,9,3): #for each row value, get all minimum column values, 0,3,6
        print(str(solvedBoard[rownum:rownum+3,column:column+3])+'\n')  #print the square using slice notation

[[5 3 4]
 [6 7 2]
 [1 9 8]]

[[6 7 8]
 [1 9 5]
 [3 4 2]]

[[9 1 2]
 [3 4 8]
 [5 6 7]]

[[8 5 9]
 [4 2 6]
 [7 1 3]]

[[7 6 1]
 [8 5 3]
 [9 2 4]]

[[4 2 3]
 [7 9 1]
 [8 5 6]]

[[9 6 1]
 [2 8 7]
 [3 4 5]]

[[5 3 7]
 [4 1 9]
 [2 8 6]]

[[2 8 4]
 [6 3 5]
 [1 7 9]]



In [74]:
# reshape the array into all the possible 2D shapes it can have. print
# each reshapedd array.


# get factors of 81, then reshape the array based on each factor
print(solvedBoard.reshape(1,81))
print(solvedBoard.reshape(3,27))
print(solvedBoard.reshape(81,1))
print(solvedBoard.reshape(27,3))
print(solvedBoard.reshape(9,9))

[[5 3 4 6 7 8 9 1 2 6 7 2 1 9 5 3 4 8 1 9 8 3 4 2 5 6 7 8 5 9 7 6 1 4 2 3
  4 2 6 8 5 3 7 9 1 7 1 3 9 2 4 8 5 6 9 6 1 5 3 7 2 8 4 2 8 7 4 1 9 6 3 5
  3 4 5 2 8 6 1 7 9]]
[[5 3 4 6 7 8 9 1 2 6 7 2 1 9 5 3 4 8 1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3 4 2 6 8 5 3 7 9 1 7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4 2 8 7 4 1 9 6 3 5 3 4 5 2 8 6 1 7 9]]
[[5]
 [3]
 [4]
 [6]
 [7]
 [8]
 [9]
 [1]
 [2]
 [6]
 [7]
 [2]
 [1]
 [9]
 [5]
 [3]
 [4]
 [8]
 [1]
 [9]
 [8]
 [3]
 [4]
 [2]
 [5]
 [6]
 [7]
 [8]
 [5]
 [9]
 [7]
 [6]
 [1]
 [4]
 [2]
 [3]
 [4]
 [2]
 [6]
 [8]
 [5]
 [3]
 [7]
 [9]
 [1]
 [7]
 [1]
 [3]
 [9]
 [2]
 [4]
 [8]
 [5]
 [6]
 [9]
 [6]
 [1]
 [5]
 [3]
 [7]
 [2]
 [8]
 [4]
 [2]
 [8]
 [7]
 [4]
 [1]
 [9]
 [6]
 [3]
 [5]
 [3]
 [4]
 [5]
 [2]
 [8]
 [6]
 [1]
 [7]
 [9]]
[[5 3 4]
 [6 7 8]
 [9 1 2]
 [6 7 2]
 [1 9 5]
 [3 4 8]
 [1 9 8]
 [3 4 2]
 [5 6 7]
 [8 5 9]
 [7 6 1]
 [4 2 3]
 [4 2 6]
 [8 5 3]
 [7 9 1]
 [7 1 3]
 [9 2 4]
 [8 5 6]
 [9 6 1]
 [5 3 7]
 [2 8 4]
 [2 8 7]
 [4 1 9]
 [6 3 5]
 [3 4 5]
 [2 8 6]
 [1 7 9]]
[[5 3 4 

In [52]:
# make a new array where the values are the sum of the rows
# summ all rows (on axis 0) and save in new array
sumRowArray = np.array(solvedBoard.sum(axis=0))

# make a new array where the values are the sum of the column
# summ all columns  (on axis 1) and save in new array
sumColumnArray = np.array(solvedBoard.sum(axis=1))
print(sumColumnArray)
print(sumRowArray)


# notice anything interesting?
# Yes -- the values in each array are eqaul to 45, this makes sense as each row and column is comprised of the same numbers 1-9

[45 45 45 45 45 45 45 45 45]
[45 45 45 45 45 45 45 45 45]


In [76]:
# make a new array where the values are the average of the rows

#same syntax as above, instead of .sum tho we use .avg

rowAvg = np.average(solvedBoard,axis=0)
# make a new array where the values are the average of the columns
colAvg = np.average(solvedBoard,axis=1)
type(rowAvg)
print(rowAvg)
print(colAvg)


# notice anything interesting?
# Yes, each value is 5, the columns have the same input

numpy.ndarray

In [59]:
# what is the average of the entire array?
np.average(solvedBoard) #5.0


5.0

In [63]:
# Make a new array where the elements are all Boolean values, representing whether or
# not the corresponding values in the solved board are odd.  (That is to say, 
# if a value is odd, the new array should have True in its corresponding location.)

# We can get a boolean version of this array by doing a true/false statement within the array. 
# Use modulo 2 to get the remainder of each value in the array / 2. If remainder ==1, number is odd 
oddOrNotArray = np.array(solvedBoard%2==1)
oddOrNotArray

array([[ True,  True, False, False,  True, False,  True,  True, False],
       [False,  True, False,  True,  True,  True,  True, False, False],
       [ True,  True, False,  True, False, False,  True, False,  True],
       [False,  True,  True,  True, False,  True, False, False,  True],
       [False, False, False, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False, False,  True, False],
       [ True, False,  True,  True,  True,  True, False, False, False],
       [False, False,  True, False,  True,  True, False,  True,  True],
       [ True, False,  True, False, False, False,  True,  True,  True]])

In [77]:
# Produce a one dimensional array of only the odd numbers in the sudoku array in the order they
# appear, e.g., [5 3 7 et cetera]

# We use boolean masking within the array to return an array where the values are only odd.
# We then create a new one dimensional array to store these values.
onlyOddArray = solvedBoard[oddOrNotArray]
onlyOddArray

array([5, 3, 7, 9, 1, 7, 1, 9, 5, 3, 1, 9, 3, 5, 7, 5, 9, 7, 1, 3, 5, 3,
       7, 9, 1, 7, 1, 3, 9, 5, 9, 1, 5, 3, 7, 7, 1, 9, 3, 5, 3, 5, 1, 7,
       9])