In [1]:
# numpy
listOfNumbers = [10,11,12,14,15]
listOfNumbers

[10, 11, 12, 14, 15]

In [2]:
listOfAListOfNumbers = [[10,12],[15,19],[20,22]]
listOfAListOfNumbers

[[10, 12], [15, 19], [20, 22]]

In [3]:
# if we wanted to add one to each number in our matrix...
for i in range(0,len(listOfNumbers)):
    listOfNumbers[i] += 1
print(listOfNumbers)

[11, 12, 13, 15, 16]


In [5]:
for i in range(0,len(listOfAListOfNumbers)):
    for j in range(0,len(listOfAListOfNumbers[i])):
        listOfAListOfNumbers[i][j] += 1
print(listOfAListOfNumbers)

[[12, 14], [16, 20], [21, 23]]


In [1]:
# there is a better way
import numpy as np
simpleNumpyArray = np.array(listOfNumbers)
simpleNumpyArray

NameError: name 'listOfNumbers' is not defined

In [7]:
type(simpleNumpyArray)

numpy.ndarray

In [8]:
simpleNumpyArray+1

array([12, 13, 14, 16, 17])

In [9]:
simpleNumpyArray

array([11, 12, 13, 15, 16])

In [10]:
# need that numpy array back in a list?
listedArray = simpleNumpyArray.tolist()
print(simpleNumpyArray)
print(listedArray)

[11 12 13 15 16]
[11, 12, 13, 15, 16]


In [12]:
# why use numpy?  it's REALLLLY fast
emptyList = []
thisGoesTo1000 = list(range(1000))
%timeit for i in range(1000):emptyList.append(i**2)

362 µs ± 18.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [13]:
numpyArray = np.arange(1000)
%timeit numpyArray**2

1.07 µs ± 23 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [14]:
myArray = np.array([1,2,3,4]) # make a new array
print(myArray)

[1 2 3 4]


In [15]:
# arange:
rangedArray = np.arange(100)
print(rangedArray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [16]:
# arange works like range
anotherRangedArray = np.arange(10,20)
print(anotherRangedArray)

[10 11 12 13 14 15 16 17 18 19]


In [17]:
steppedRangedArray = np.arange(37,50,2) # using a stepsize of 2
print(steppedRangedArray)

[37 39 41 43 45 47 49]


In [19]:
# shapes and types
myBadList = [3,4,"howdy"]
myBadArray = np.array(myBadList)
print(myBadArray)

['3' '4' 'howdy']


In [20]:
# they all became strings!  eep!
print(myBadArray*2)
# you get an error because numpy doesn't know how to multiply strings

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')

In [21]:
print(myBadArray.dtype) # .dtype is an np object property

<U21


In [22]:
print(steppedRangedArray.dtype)

int64


In [23]:
steppedRangedArray*2

array([74, 78, 82, 86, 90, 94, 98])

In [26]:
a2DArray = np.array([[1,2],[2,3],[3,4]])
print(a2DArray)

[[1 2]
 [2 3]
 [3 4]]


In [27]:
print(a2DArray.shape) # shape is a np array property that gives you the row, column dimensions

(3, 2)


In [28]:
print(a2DArray.dtype) # dtype gives you the datatype of the *data* in the array

int64


In [29]:
type(a2DArray)

numpy.ndarray

In [30]:
# get items from an array
print(a2DArray[2][1])

4


In [31]:
# numpy has a special accessor syntax
print(a2DArray[2,1]) # we use commas instead of separate brackets

4


In [34]:
# you can slice numpy arrays
print(a2DArray[1:])

[[2 3]
 [3 4]]


In [35]:
print(a2DArray)

[[1 2]
 [2 3]
 [3 4]]


In [33]:
# if you only wanted the first column?
print(a2DArray[0:,0])

[1 2 3]


In [36]:
print(a2DArray[:,0])# this says give me every row but only the first column

[1 2 3]


In [37]:
aBigger2DArray = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
print(aBigger2DArray)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [38]:
# give me every other row and every other column
print(aBigger2DArray[::2,::2])

[[ 0  2  4]
 [10 12 14]]


In [39]:
# generate an array with a certain number of points between and including a start and stop
evenlySep = np.linspace(0,100,40) # this makes an array with numbers that start at 0 and end
# at 100 and contains 40 points
print(evenlySep)

[  0.           2.56410256   5.12820513   7.69230769  10.25641026
  12.82051282  15.38461538  17.94871795  20.51282051  23.07692308
  25.64102564  28.20512821  30.76923077  33.33333333  35.8974359
  38.46153846  41.02564103  43.58974359  46.15384615  48.71794872
  51.28205128  53.84615385  56.41025641  58.97435897  61.53846154
  64.1025641   66.66666667  69.23076923  71.79487179  74.35897436
  76.92307692  79.48717949  82.05128205  84.61538462  87.17948718
  89.74358974  92.30769231  94.87179487  97.43589744 100.        ]


In [19]:
# we can also create an array with random data
randomArray = np.random.randint(10,20,size=10)
# generates an array of 10 numbers that start at 10 up to but not including 20
print(randomArray)

[18 12 15 16 16 11 12 11 11 11]


In [9]:
random2DArray = np.random.randint(10,20,size=(5,2)) # creates a random 2D array of 5 rows and
# 2 columns with numbers between 10 and 19
print(random2DArray) 

[[15 14]
 [14 16]
 [11 12]
 [12 12]
 [15 14]]


In [2]:
import numpy as np

In [20]:
# get 5 random numbers from random2DArray
print(np.random.choice(randomArray,size=5))
# each grab is random, so you can have a number from randomArray in the new array multiple
# times

[18 18 12 16 11]


In [21]:
# shuffle an array
np.random.shuffle(randomArray)

In [22]:
print(randomArray)
# note that shuffle doesn't return the array, but actually modifies it.

[11 18 12 12 11 16 15 11 11 16]


In [23]:
shuffledArrayResult = np.random.shuffle(randomArray)

In [24]:
print(shuffledArrayResult)

None


In [25]:
print(randomArray)

[12 11 16 16 12 15 11 11 11 18]


In [26]:
# use random to create a normal distribution of numbers
normallyDist = np.random.normal(100,10,150)
print(normallyDist)
# 100: mean
# 10: standard deviation
# 150: number of datapoints in the array we've created

[ 87.89103979  97.77357965 114.16684155 103.35419372  87.82353079
 111.10106179 118.74753801  99.37721285 114.2000372   90.67951986
  82.70183204 106.36721296  82.8188886  108.69989522  93.57755842
 104.42109078 100.18896573 100.10775111 103.14773298  91.14133785
 105.46059189 120.52145114  91.73575321 101.0776078  125.09950746
  95.5869519  107.14583613  94.25926573 114.84074437 101.82488165
 105.90062538 102.01311024 100.95780147  96.60612693  95.79602563
  75.37556516 106.555398    93.40229452 105.55026312  96.24092266
  99.79101495 107.73121121 104.26985583  96.07125828 110.73780165
 111.174873   106.76107693  90.64137059  90.87064611  88.5921673
  82.16051846 111.03699078  98.68303962 109.77031258 108.53457872
  97.67187651 101.50689568  88.8406055   99.85884892  89.39841057
  79.48915626 114.88966238  99.60441839  93.85239981  94.9624404
  96.11214381 107.26296049 104.79186062  87.01760616  81.52526761
 111.12776021 101.64383312 106.81724892  95.61769519  92.02725412
  99.4065664

In [27]:
# we can join arrays using the concatenate method
zeroThroughFour = np.arange(0,5)
fiveThroughNine = np.arange(5,10)
zeroThroughNine = np.concatenate((zeroThroughFour,fiveThroughNine))
# concatenate takes a tuple of arrays that you want to concatenate
print(zeroThroughFour)
print(fiveThroughNine)
print(zeroThroughNine)

[0 1 2 3 4]
[5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [28]:
print(np.concatenate((fiveThroughNine,zeroThroughFour))) # the order of the arrays in the tuple
# matters

[5 6 7 8 9 0 1 2 3 4]


In [29]:
# reshaping
hundyArray = np.arange(1,101)
print(hundyArray)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [30]:
# let's reshape this array
reshapedHundyArray = hundyArray.reshape((10,10))
print(reshapedHundyArray)
# important things to note: reshape doesn't modify the existing array, but it returns 
# a new array
# you can only reshape into a size where all of the cells of the matrix are full

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [31]:
hundyArray.reshape(((10,9)))

ValueError: cannot reshape array of size 100 into shape (10,9)

In [32]:
# what other array sizes can we reshape hundyArray into?
# any size where the product of the dimensions equals 100
print(hundyArray.reshape((25,4)))

[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [ 13  14  15  16]
 [ 17  18  19  20]
 [ 21  22  23  24]
 [ 25  26  27  28]
 [ 29  30  31  32]
 [ 33  34  35  36]
 [ 37  38  39  40]
 [ 41  42  43  44]
 [ 45  46  47  48]
 [ 49  50  51  52]
 [ 53  54  55  56]
 [ 57  58  59  60]
 [ 61  62  63  64]
 [ 65  66  67  68]
 [ 69  70  71  72]
 [ 73  74  75  76]
 [ 77  78  79  80]
 [ 81  82  83  84]
 [ 85  86  87  88]
 [ 89  90  91  92]
 [ 93  94  95  96]
 [ 97  98  99 100]]


In [33]:
print(hundyArray.reshape((50,2)))

[[  1   2]
 [  3   4]
 [  5   6]
 [  7   8]
 [  9  10]
 [ 11  12]
 [ 13  14]
 [ 15  16]
 [ 17  18]
 [ 19  20]
 [ 21  22]
 [ 23  24]
 [ 25  26]
 [ 27  28]
 [ 29  30]
 [ 31  32]
 [ 33  34]
 [ 35  36]
 [ 37  38]
 [ 39  40]
 [ 41  42]
 [ 43  44]
 [ 45  46]
 [ 47  48]
 [ 49  50]
 [ 51  52]
 [ 53  54]
 [ 55  56]
 [ 57  58]
 [ 59  60]
 [ 61  62]
 [ 63  64]
 [ 65  66]
 [ 67  68]
 [ 69  70]
 [ 71  72]
 [ 73  74]
 [ 75  76]
 [ 77  78]
 [ 79  80]
 [ 81  82]
 [ 83  84]
 [ 85  86]
 [ 87  88]
 [ 89  90]
 [ 91  92]
 [ 93  94]
 [ 95  96]
 [ 97  98]
 [ 99 100]]


In [34]:
print(hundyArray.reshape((100,1)))

[[  1]
 [  2]
 [  3]
 [  4]
 [  5]
 [  6]
 [  7]
 [  8]
 [  9]
 [ 10]
 [ 11]
 [ 12]
 [ 13]
 [ 14]
 [ 15]
 [ 16]
 [ 17]
 [ 18]
 [ 19]
 [ 20]
 [ 21]
 [ 22]
 [ 23]
 [ 24]
 [ 25]
 [ 26]
 [ 27]
 [ 28]
 [ 29]
 [ 30]
 [ 31]
 [ 32]
 [ 33]
 [ 34]
 [ 35]
 [ 36]
 [ 37]
 [ 38]
 [ 39]
 [ 40]
 [ 41]
 [ 42]
 [ 43]
 [ 44]
 [ 45]
 [ 46]
 [ 47]
 [ 48]
 [ 49]
 [ 50]
 [ 51]
 [ 52]
 [ 53]
 [ 54]
 [ 55]
 [ 56]
 [ 57]
 [ 58]
 [ 59]
 [ 60]
 [ 61]
 [ 62]
 [ 63]
 [ 64]
 [ 65]
 [ 66]
 [ 67]
 [ 68]
 [ 69]
 [ 70]
 [ 71]
 [ 72]
 [ 73]
 [ 74]
 [ 75]
 [ 76]
 [ 77]
 [ 78]
 [ 79]
 [ 80]
 [ 81]
 [ 82]
 [ 83]
 [ 84]
 [ 85]
 [ 86]
 [ 87]
 [ 88]
 [ 89]
 [ 90]
 [ 91]
 [ 92]
 [ 93]
 [ 94]
 [ 95]
 [ 96]
 [ 97]
 [ 98]
 [ 99]
 [100]]


In [35]:
threeByThree = np.array([[1,2,3],[4,5,6],[7,8,9]]) # reminder: list of lists to make a 2D array

In [36]:
print(threeByThree)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
transposed = threeByThree.transpose()
print(transposed)
# rows become columns, columns become rows

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [38]:
# we can flatten an array into one row
flattened = threeByThree.flatten()
print(flattened)

[1 2 3 4 5 6 7 8 9]


In [40]:
print(transposed.flatten())

[1 4 7 2 5 8 3 6 9]


In [41]:
# element-wise operations
oneDArray = np.array([1,2,3,4,5,6])
anotherOneDArray = np.array([0,19,2,3,18,4])
print(oneDArray*4)

[ 4  8 12 16 20 24]


In [42]:
print(oneDArray)

[1 2 3 4 5 6]


In [43]:
# you can add, subtract, multiple, divide, comparison, modulo
print(oneDArray > anotherOneDArray)

[ True False  True  True False  True]


In [44]:
aThirdOneDArray = np.array([1,2,3])

In [45]:
print(oneDArray > aThirdOneDArray)
# you get an error because the arrays are not the same size

ValueError: operands could not be broadcast together with shapes (6,) (3,) 

In [46]:
print(oneDArray + anotherOneDArray)

[ 1 21  5  7 23 10]


In [47]:
print(oneDArray + aThirdOneDArray)

ValueError: operands could not be broadcast together with shapes (6,) (3,) 

In [ ]:
# you can also do dot products with the .dot method

In [48]:
# aggregation functions
evenArray = np.arange(0,7,2).reshape(2,2)
print(evenArray)

[[0 2]
 [4 6]]


In [49]:
print(evenArray.sum())
# sum just sums up all the values in evenArray: 0 + 2 + 4 + 6 = 12

12


In [50]:
print(evenArray.sum(axis=0)) # adding elements across rows

[4 8]


In [51]:
print(evenArray.sum(axis=1)) # adding elements across columns

[ 2 10]


In [52]:
print(evenArray.min()) # grabs minimum value in entire array

0


In [53]:
print(evenArray.max()) # grabs max value in an entire array

6


In [55]:
print(evenArray.min(axis=0))
print(evenArray.min(axis=1))

[0 2]
[0 4]


In [56]:
print(evenArray.prod()) # gets the product of all the numbers in the array

0


In [3]:
import numpy as np
oddArray = np.arange(1,9,2).reshape((2,2))
print(oddArray)
print(oddArray.prod()) # product gets the product of every number in the array
# as before, you can specify axes here

[[1 3]
 [5 7]]
105


In [62]:
# calculate averages
print(evenArray)
print(np.average(evenArray))
print(np.average(oddArray))
# you can also specify axes with average as well

[[0 2]
 [4 6]]
3.0
4.0


In [63]:
print(np.average(evenArray,axis=0))
print(np.average(evenArray,axis=1))

[2. 4.]
[1. 5.]
