In [2]:
#reason for numby
listOfNumbers =[10,9,8,7,6,5]
listOfNumbers
#to add one to each number we 
for i in listOfNumbers:
    listOfNumbers[10-i]+=1   # <----- rather complex way of doing it, is there a better way? 
print(listOfNumbers)


[11, 10, 9, 8, 7, 6]


In [3]:
#Numpy for arrays!
import numpy as np 
numpyArray = np.array(listOfNumbers)  #<--- puts list of numbers in specifified numpy array 
print(numpyArray)
numpyArray = numpyArray+1
print(numpyArray)

#can convert back to list (numpyObject.tolist())

listedArray = numpyArray.tolist()
print("\n{0}".format(listedArray))



[11 10  9  8  7  6]
[12 11 10  9  8  7]

[12, 11, 10, 9, 8, 7]


In [4]:
#Why numpy? ITS SUPER FAST 
emptyList =[]
thisGoesTo100 = list(range(100))
%timeit for i in range(1000):emptyList.append(i**2)
print("")
newArray = np.arange(1000)
%timeit newArray**2

556 µs ± 39.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

3.7 µs ± 126 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
#Numpy methods:
#create new array: .array
myArray = np.array([1,2,3,4,5,6])

#arange: Works like range ---> np.arange(min,max,stepsize)
rangedArray = np.arange(100)
stepRangedArray = np.arange(30,51,2)
print(stepRangedArray)

#SHAPES AND TYPES 
myBadList = [3,4,"howdy"]
badArray = np.array(myBadList)  #<---- everything becomes a string! Yikes !

#.dtype is an np object property # gives u datatype of *data* in the array
print(badArray.dtype)  
print(stepRangedArray.dtype)
stepRangedArray*2   #becase we know type of array(int) here, we can multiple by 2 for specific arrray 

#Shape gives you the row, column dimensions of the array
a2DArray = np.array([[1,2],[3,4],[5,6]])
print(a2DArray)
print(a2DArray.shape)

#Get items from array:
print(a2DArray[2][0])
#NUMPY HAS SPECIAL ACCESSOR SYNTAX
print(a2DArray[1,0]) #uses commas instead of seperate brackets 

[30 32 34 36 38 40 42 44 46 48 50]
<U11
int32
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
5
3


In [76]:
#NUMPY Arrays contd.. slicing: 
print(a2DArray)
print()

#last row
print(a2DArray[2:])
#second row and below?
print(a2DArray[1:])
#First column
print(a2DArray[0:,0])
#second column
print(a2DArray[0:,1])
print(a2DArray[:,0])# this says give me every row but only the first column

[[1 2]
 [3 4]
 [5 6]]

[[5 6]]
[[3 4]
 [5 6]]
[1 3 5]
[2 4 6]
[1 3 5]


In [6]:
import numpy as np 
import pandas as pd 

gamelogsDF = pd.read_csv('GL2016.TXT',header=None)
gamelogsDF.columns = range(1,len(gamelogsDF.columns)+1)
gamelogsDF["seasonYear"]=2016
gamelogsDF.head()

1  2    3    4   5  6    7   8  9  10  ...  153       154  \
0  20160403  0  Sun  NYN  NL  1  KCA  AL  1   3  ...    2  infao001   
1  20160403  0  Sun  TOR  AL  1  TBA  AL  1   5  ...    9  kierk001   
2  20160403  0  Sun  SLN  NL  1  PIT  NL  1   1  ...    4  mercj002   
3  20160404  0  Mon  CHN  NL  1  ANA  AL  1   9  ...    6  perec003   
4  20160404  0  Mon  MIN  AL  1  BAL  AL  1   2  ...    6  schoj001   

               155 156       157                158 159  160  161 seasonYear  
0     Omar Infante   4  fuenr001    Reymond Fuentes   9  NaN    Y       2016  
1  Kevin Kiermaier   8  congh001        Hank Conger   2  NaN    Y       2016  
2     Jordy Mercer   6  lirif001  Francisco Liriano   1  NaN    Y       2016  
3     Carlos Perez   2  giavj001  Johnny Giavotella   4  NaN    Y       2016  
4  Jonathan Schoop   4  rickj001       Joey Rickard   7  NaN    Y       2016  

[5 rows x 162 columns]

In [13]:
#grab speciifc columns columns, we use notation similar to numpys selecgtion notation. 
#specify a column seperated list of column names 
#the far left column isnt really a column
gamelogsDF[[1,4,"seasonYear"]].head(3)


1    4  seasonYear
0  20160403  NYN        2016
1  20160403  TOR        2016
2  20160403  SLN        2016

In [17]:
#to grab specific rows, we use the loc attribute
gamelogsDF.loc[2] #<----- this a pandas serires object, all values are returned in a dictionary like fromat where the keys are the column labels
                  #        and the values are the data points. loc is looking for the names of rows.
gamelogsDF.loc[2][4]


'SLN'

In [19]:
gamelogsDF.loc[0:3]

1  2    3    4   5  6    7   8  9  10  ...  153       154  \
0  20160403  0  Sun  NYN  NL  1  KCA  AL  1   3  ...    2  infao001   
1  20160403  0  Sun  TOR  AL  1  TBA  AL  1   5  ...    9  kierk001   
2  20160403  0  Sun  SLN  NL  1  PIT  NL  1   1  ...    4  mercj002   
3  20160404  0  Mon  CHN  NL  1  ANA  AL  1   9  ...    6  perec003   

               155 156       157                158 159  160  161 seasonYear  
0     Omar Infante   4  fuenr001    Reymond Fuentes   9  NaN    Y       2016  
1  Kevin Kiermaier   8  congh001        Hank Conger   2  NaN    Y       2016  
2     Jordy Mercer   6  lirif001  Francisco Liriano   1  NaN    Y       2016  
3     Carlos Perez   2  giavj001  Johnny Giavotella   4  NaN    Y       2016  

[4 rows x 162 columns]

In [20]:
gamelogsDF.loc[0:10:2]

1  2    3    4   5  6    7   8  9  10  ...  153       154  \
0   20160403  0  Sun  NYN  NL  1  KCA  AL  1   3  ...    2  infao001   
2   20160403  0  Sun  SLN  NL  1  PIT  NL  1   1  ...    4  mercj002   
4   20160404  0  Mon  MIN  AL  1  BAL  AL  1   2  ...    6  schoj001   
6   20160404  0  Mon  TOR  AL  2  TBA  AL  2   5  ...    9  kierk001   
8   20160404  0  Mon  COL  NL  1  ARI  NL  1  10  ...    5  greiz001   
10  20160404  0  Mon  PHI  NL  1  CIN  NL  1   2  ...    7  igler001   

                155 156       157                158 159  160  161 seasonYear  
0      Omar Infante   4  fuenr001    Reymond Fuentes   9  NaN    Y       2016  
2      Jordy Mercer   6  lirif001  Francisco Liriano   1  NaN    Y       2016  
4   Jonathan Schoop   4  rickj001       Joey Rickard   7  NaN    Y       2016  
6   Kevin Kiermaier   8  casac001        Curt Casali   2  NaN    Y       2016  
8      Zack Greinke   1  ahmen001         Nick Ahmed   6  NaN    Y       2016  
10  Raisel Iglesias   1  hamib001     Billy Hamilton   8  NaN    Y       2016  

[6 rows x 162 columns]

In [22]:
gamelogsDF.loc[::5]

1  2    3    4   5    6    7   8    9  10  ...  153       154  \
0     20160403  0  Sun  NYN  NL    1  KCA  AL    1   3  ...    2  infao001   
5     20160404  0  Mon  CHA  AL    1  OAK  AL    1   4  ...    3  vogts001   
10    20160404  0  Mon  PHI  NL    1  CIN  NL    1   2  ...    7  igler001   
15    20160405  0  Tue  NYN  NL    2  KCA  AL    2   2  ...    2  infao001   
20    20160405  0  Tue  COL  NL    2  ARI  NL    2   6  ...    7  mills001   
...        ... ..  ...  ...  ..  ...  ...  ..  ...  ..  ...  ...       ...   
2405  20161001  0  Sat  SDN  NL  161  ARI  NL  161   5  ...    5  herno002   
2410  20161001  0  Sat  LAN  NL  161  SFN  NL  161   0  ...    5  panij002   
2415  20161002  0  Sun  MIN  AL  162  CHA  AL  162   6  ...    2  sancc001   
2420  20161002  0  Sun  SDN  NL  162  ARI  NL  162   2  ...    8  goset001   
2425  20161002  0  Sun  LAN  NL  162  SFN  NL  162   1  ...    4  gillc001   

                  155 156       157              158 159  160  161 seasonYear  
0        Omar Infante   4  fuenr001  Reymond Fuentes   9  NaN    Y       2016  
5        Stephen Vogt   2  semim001    Marcus Semien   6  NaN    Y       2016  
10    Raisel Iglesias   1  hamib001   Billy Hamilton   8  NaN    Y       2016  
15       Omar Infante   4  fuenr001  Reymond Fuentes   9  NaN    Y       2016  
20      Shelby Miller   1  ahmen001       Nick Ahmed   6  NaN    Y       2016  
...               ...  ..       ...              ...  ..  ...  ...        ...  
2405  Oscar Hernandez   2  brada001   Archie Bradley   1  NaN    Y       2016  
2410        Joe Panik   4  blact002         Ty Blach   1  NaN    Y       2016  
2415   Yolmer Sanchez   4  garcl004     Leury Garcia   8  NaN    Y       2016  
2420  Tuffy Gosewisch   2  kochm001        Matt Koch   1  NaN    Y       2016  
2425  Conor Gillaspie   5  moorm003       Matt Moore   1  NaN    Y       2016  

[486 rows x 162 columns]

In [23]:
gamelogsDF.loc[[0,1,2,44,55]] # can specify list of rows 

1  2    3    4   5  6    7   8  9  10  ...  153       154  \
0   20160403  0  Sun  NYN  NL  1  KCA  AL  1   3  ...    2  infao001   
1   20160403  0  Sun  TOR  AL  1  TBA  AL  1   5  ...    9  kierk001   
2   20160403  0  Sun  SLN  NL  1  PIT  NL  1   1  ...    4  mercj002   
44  20160407  0  Thu  LAN  NL  4  SFN  NL  4   6  ...    6  peavj001   
55  20160408  0  Fri  PIT  NL  4  CIN  NL  4   6  ...    7  simoa001   

                155 156       157                158 159  160  161 seasonYear  
0      Omar Infante   4  fuenr001    Reymond Fuentes   9  NaN    Y       2016  
1   Kevin Kiermaier   8  congh001        Hank Conger   2  NaN    Y       2016  
2      Jordy Mercer   6  lirif001  Francisco Liriano   1  NaN    Y       2016  
44       Jake Peavy   1  pagaa001        Angel Pagan   7  NaN    Y       2016  
55    Alfredo Simon   1  hamib001     Billy Hamilton   8  NaN    Y       2016  

[5 rows x 162 columns]

In [25]:
gamelogsDF.loc[[0,1,2,44,55],[1,2,3,"seasonYear"]] # can specify list of rows and columns 
                                                    # this is just like numpy syntax
                                                    # pandas uses numpy underneath to reckognize data
                                                    

1  2    3  seasonYear
0   20160403  0  Sun        2016
1   20160403  0  Sun        2016
2   20160403  0  Sun        2016
44  20160407  0  Thu        2016
55  20160408  0  Fri        2016

In [26]:
#every row and the first three columns 
gamelogsDF.loc[:,[1,2,3]]

1  2    3
0     20160403  0  Sun
1     20160403  0  Sun
2     20160403  0  Sun
3     20160404  0  Mon
4     20160404  0  Mon
...        ... ..  ...
2423  20161002  0  Sun
2424  20161002  0  Sun
2425  20161002  0  Sun
2426  20161002  0  Sun
2427  20161002  0  Sun

[2428 rows x 3 columns]